# Generated by Django 3.2.9 on 2021-12-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizez', '0002_quiz_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Intermediate', 'Intermediate'), ('Hard', 'Hard')], default='Select', max_length=12),
        ),
    ]
